In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
df = pd.read_csv("data/cardekho_data.csv")

In [28]:
df.head()

,Car_Name,Year,SellingPrice,PresentPrice,KmsDriven,FuelType,SellerType,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0


In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Car_Name      301 non-null    object 
 1   Year          301 non-null    int64  
 2   SellingPrice  301 non-null    float64
 3   PresentPrice  301 non-null    float64
 4   KmsDriven     301 non-null    int64  
 5   FuelType      301 non-null    object 
 6   SellerType    301 non-null    object 
 7   Transmission  301 non-null    object 
 8   Owner         301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [30]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Car_Name'] = le.fit_transform(df['Car_Name'])
df['FuelType'] = le.fit_transform(df['FuelType'])
df['SellerType'] = le.fit_transform(df['SellerType'])
df['Transmission'] = le.fit_transform(df['Transmission'])

print(df.head())

   Car_Name  Year  SellingPrice  PresentPrice  KmsDriven  FuelType  \
0        90  2014          3.35          5.59      27000         2   
1        93  2013          4.75          9.54      43000         1   
2        68  2017          7.25          9.85       6900         2   
3        96  2011          2.85          4.15       5200         2   
4        92  2014          4.60          6.87      42450         1   

   SellerType  Transmission  Owner  
0           0             1      0  
1           0             1      0  
2           0             1      0  
3           0             1      0  
4           0             1      0  


In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Car_Name      301 non-null    int64  
 1   Year          301 non-null    int64  
 2   SellingPrice  301 non-null    float64
 3   PresentPrice  301 non-null    float64
 4   KmsDriven     301 non-null    int64  
 5   FuelType      301 non-null    int64  
 6   SellerType    301 non-null    int64  
 7   Transmission  301 non-null    int64  
 8   Owner         301 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 21.3 KB


In [32]:
df.dropna(how='any', inplace=True)

In [33]:
len(df)

301

In [34]:
df.columns

Index(['Car_Name', 'Year', 'SellingPrice', 'PresentPrice', 'KmsDriven',
       'FuelType', 'SellerType', 'Transmission', 'Owner'],
      dtype='object')

In [35]:
df.SellingPrice.value_counts()

SellingPrice
0.45     8
0.60     8
5.25     7
4.50     7
0.20     6
        ..
3.80     1
3.45     1
5.90     1
35.00    1
11.50    1
Name: count, Length: 156, dtype: int64

In [36]:
x=df.drop(["SellingPrice"],axis=1)

In [37]:
y=df.SellingPrice.values

In [38]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [39]:
len(x_train)

240

In [40]:
len(x_test)

61

In [41]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)
x_train_sc = sc.transform(x_train)
x_test_sc = sc.transform(x_test)


In [42]:
x_train_sc

array([[ 0.05028543,  0.17348659, -0.4624877 , ..., -0.74728947,
         0.38513031, -0.16351749],
       [ 0.36173064,  0.83438786,  0.79836605, ..., -0.74728947,
         0.38513031, -0.16351749],
       [-1.03977282,  0.50393722, -0.76473961, ...,  1.33816952,
         0.38513031, -0.16351749],
       ...,
       [-0.72832761,  0.50393722, -0.5827266 , ...,  1.33816952,
         0.38513031, -0.16351749],
       [ 0.40066129,  0.83438786,  0.65606497, ..., -0.74728947,
         0.38513031, -0.16351749],
       [ 0.36173064, -0.81786533,  0.6715085 , ..., -0.74728947,
         0.38513031, -0.16351749]], shape=(240, 8))

In [43]:
x_test_sc

array([[-1.7794552 , -0.15696405, -0.73495566,  0.1675021 ,  0.46114399,
         1.33816952,  0.38513031, -0.16351749],
       [ 0.98462106, -1.14831597, -0.01683161,  0.55889652,  0.46114399,
        -0.74728947,  0.38513031, -0.16351749],
       [ 0.24493868,  0.50393722,  0.30086383,  0.31243616, -2.05418686,
        -0.74728947,  0.38513031, -0.16351749],
       [ 0.24493868,  0.17348659,  0.48397995, -0.55716818,  0.46114399,
        -0.74728947, -2.59652373, -0.16351749],
       [ 0.94569041,  0.83438786,  1.95663066, -0.21898872, -2.05418686,
        -0.74728947, -2.59652373, -0.16351749],
       [ 0.7121065 , -0.81786533, -0.21428814,  0.11919075,  0.46114399,
        -0.74728947,  0.38513031, -0.16351749],
       [ 0.24493868,  0.83438786,  0.13650056, -0.4297953 , -2.05418686,
        -0.74728947,  0.38513031, -0.16351749],
       [-0.26115979, -1.14831597, -0.78680179, -0.38807845,  0.46114399,
         1.33816952, -2.59652373, -0.16351749],
       [ 0.75103715, -0.48741469

In [44]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()

model.fit(x_train_sc, y_train)




,"criterion criterion: {""squared_error"", ""friedman_mse"", ""absolute_error"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""friedman_mse"", which usesmean squared error with Friedman's improvement score for potentialsplits, ""absolute_error"" for the mean absolute error, which minimizesthe L1 loss using the median of each terminal node, and ""poisson"" whichuses reduction in the half mean Poisson deviance to find splits... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 0.24 Poisson deviance criterion.",'squared_error'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.For an example of how ``max_depth`` influences the model, see:ref:`sphx_glr_auto_examples_tree_plot_tree_regression.py`.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",None
,"max

In [45]:
y_pred = model.predict(x_test_sc)

In [53]:
y_pred.astype(int)

array([ 0,  2,  7,  7, 23,  4,  7,  0, 14,  4,  5,  6,  5,  4,  0,  5,  7,
        4,  0,  3,  5,  1,  6,  0,  0,  2,  2,  7,  7,  0,  4,  0,  5,  1,
        4,  8,  3,  5, 14,  1,  7,  5,  5,  4,  7,  5,  5,  2,  5,  1,  0,
       11,  4,  5,  5,  0,  0,  0,  1,  5,  1])

In [54]:
y_test.astype(int)

array([ 0,  2,  6,  7, 20,  2,  8,  0, 14,  4,  5,  5,  6,  4,  0,  6,  7,
        2,  0,  3,  6,  1,  6,  0,  0,  3,  1,  7,  6,  0,  4,  0,  4,  1,
        3, 11,  6,  3, 16,  1,  8,  4,  7,  5,  7,  5,  3,  2,  4,  1,  0,
       11,  4,  6,  5,  0,  0,  0,  1,  3,  1])

In [57]:
from sklearn.metrics import accuracy_score

print(round(accuracy_score(y_test.astype(int),y_pred.astype(int))*100,2))

57.38
