In [337]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [338]:
df = pd.read_csv("data/Heart_Disease_Prediction.csv")

In [339]:
df.head(100)

,Age,Gender,Chest_pain _type,BP,Cholesterol,FBS_over_120,EKG_results,Max_HR,Exercise_angina,ST_depression,Slope_of_ST,Number_of_vessels_fluro,Thallium,Heart_Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,47,1,4,110,275,0,2,118,1,1.0,2,1,3,Presence
96,66,1,4,120,302,0,2,151,0,0.4,2,0,3,Absence
97,58,1,4,100,234,0,0,156,0,0.1,1,1,7,Presence
98,64,0,3,140,313,0,0,133,0,0.2,1,0,7,Absence


In [340]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Age                      270 non-null    int64  
 1   Gender                   270 non-null    int64  
 2   Chest_pain _type         270 non-null    int64  
 3   BP                       270 non-null    int64  
 4   Cholesterol              270 non-null    int64  
 5   FBS_over_120             270 non-null    int64  
 6   EKG_results              270 non-null    int64  
 7   Max_HR                   270 non-null    int64  
 8   Exercise_angina          270 non-null    int64  
 9   ST_depression            270 non-null    float64
 10  Slope_of_ST              270 non-null    int64  
 11  Number_of_vessels_fluro  270 non-null    int64  
 12  Thallium                 270 non-null    int64  
 13  Heart_Disease            270 non-null    object 
dtypes: float64(1), int64(12), 

In [341]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Heart_Disease'] = le.fit_transform(df['Heart_Disease'])

print(df.head(10))

   Age  Gender  Chest_pain _type   BP  Cholesterol  FBS_over_120  EKG_results  \
0   70       1                 4  130          322             0            2   
1   67       0                 3  115          564             0            2   
2   57       1                 2  124          261             0            0   
3   64       1                 4  128          263             0            0   
4   74       0                 2  120          269             0            2   
5   65       1                 4  120          177             0            0   
6   56       1                 3  130          256             1            2   
7   59       1                 4  110          239             0            2   
8   60       1                 4  140          293             0            2   
9   63       0                 4  150          407             0            2   

   Max_HR  Exercise_angina  ST_depression  Slope_of_ST  \
0     109                0            2.4         

In [342]:
df.dropna(how='any',inplace=True)

In [343]:
len(df)

270

In [344]:
df.columns

Index(['Age', 'Gender', 'Chest_pain _type', 'BP', 'Cholesterol',
       'FBS_over_120', 'EKG_results', 'Max_HR', 'Exercise_angina',
       'ST_depression', 'Slope_of_ST', 'Number_of_vessels_fluro', 'Thallium',
       'Heart_Disease'],
      dtype='object')

In [345]:
df.Heart_Disease.value_counts()

Heart_Disease
0    150
1    120
Name: count, dtype: int64

In [346]:
X = df.drop(['Heart_Disease'],axis=1)

In [347]:
Y = df.Heart_Disease.values

In [348]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.25)

In [349]:
len(X_train)

202

In [350]:
len(X_test)

68

In [351]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.fit_transform(X_test)

In [352]:
X_train_sc

array([[-0.11853008, -1.48537847,  0.86607143, ...,  0.66019691,
        -0.73057576, -0.95454841],
       [ 0.44351395,  0.67322909,  0.86607143, ...,  0.66019691,
         2.50102211,  1.0967152 ],
       [ 0.33110515,  0.67322909, -0.17527636, ...,  0.66019691,
         0.34662353,  1.0967152 ],
       ...,
       [-1.46743575,  0.67322909,  0.86607143, ..., -0.98622008,
        -0.73057576,  1.0967152 ],
       [ 0.89314917, -1.48537847,  0.86607143, ...,  0.66019691,
        -0.73057576, -0.95454841],
       [-0.23093888,  0.67322909, -2.25797195, ...,  0.66019691,
        -0.73057576,  0.58389929]], shape=(202, 13))

In [353]:
X_test_sc

array([[ 1.19639084, -1.3540064 ,  0.88721218, -1.47649248, -0.4956462 ,
        -0.43929769, -0.92921051, -0.22462179, -0.71492035, -0.56193296,
        -0.8656303 ,  1.37820949, -0.66572127],
       [-0.05843554,  0.73854895, -1.30662158, -0.01610719,  0.45341786,
        -0.43929769, -0.92921051,  0.28846777, -0.71492035, -0.82606735,
        -0.8656303 , -0.65914367, -0.66572127],
       [ 1.19639084,  0.73854895,  0.88721218, -0.62460106, -0.15495654,
        -0.43929769, -0.92921051, -3.02688013, -0.71492035,  0.05438061,
         0.72525782, -0.65914367, -0.66572127],
       [-1.41783079,  0.73854895,  0.88721218,  0.59238668, -0.42264127,
        -0.43929769, -0.92921051,  1.1962416 , -0.71492035, -0.82606735,
        -0.8656303 , -0.65914367, -0.66572127],
       [-1.20869306,  0.73854895, -1.30662158, -0.62460106, -0.56865112,
        -0.43929769, -0.92921051,  0.88049418, -0.71492035, -0.82606735,
        -0.8656303 , -0.65914367, -0.66572127],
       [-0.16300441, -1.354006

In [354]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=5)

model_knn.fit(X_train_sc, Y_train)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.Doesn't affect :meth:`fit` method.",None


In [355]:
Y_pred_knn = model_knn.predict(X_test_sc)

In [356]:
Y_pred_knn

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1])

In [357]:
Y_test

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1])

In [358]:
from sklearn.metrics import accuracy_score

print(round(accuracy_score(Y_test, Y_pred_knn)*100,2))

82.35


In [359]:
df.to_csv("knn2.csv",index=False)